### ISSUE TITLE
X and Y positions are wrong

### ISSUE THREAD

**Issue by aglalit** [uArm-Developer/SwiftProForArduino#12]
Hi, I tried to use your firmware, the speed is very good, it's exactly what I need, but X and Y positions it gets with G0 or G1 are completely wrong, out of range etc. Spent all day trying to figure out what is the cause, but nothing helps. Please help.

**Comment by TopgunZh** [comment]
Hi,can you give me more details？How did you test it？You can show me some picture.Thanks.

**Comment by aglalit** [comment]
Yes, (sorry for delay) I've just tested it with uArm Python SDK example (test.py) and it works like on the video ([the link](https://drive.google.com/file/d/1oGn4Ty0-fpAQTwy8wXlyS4fFyOMOcjmN/view?usp=sharing)). Also, on firmware 4.1.1 it is infinitely beeping (4.1.0 doesn't beep).

I was very excited to get the new level of speed (I need the arm for synthesizer playing, but unfortunately v3 firmware was too slow), but I can't handle this errors. It is the uArm Swift Pro from the first Kickstarter campaign, if it is important to tell. Thanks for help.

**Comment by aglalit** [comment]
@TopgunZh Thank you for fixing this! I'm so happy!
