### ISSUE TITLE
G0 and G1 command use meters for Y value

### ISSUE THREAD

**Issue by normen** [uArm-Developer/SwiftProForArduino#3]
When sending GCODE to the uArm Swift Pro with Firmware 3.1.9:
The G0 and G1 commands cause the uArm to move in millimeters in the X and Z axis, the value for the Y axis seems to be in meters.

**Comment by normen** [comment]
This is the case in "Laser Mode" (M2400 S1)

**Comment by yuntian1019** [comment]
Hi, normen, All X Y Z are move in millimeters, please double check your GCODE. If the problem still exists, it may be a hardware problem.

**Comment by normen** [comment]
Hm, I was just about to make a video of it and now it doesn't happen anymore.. I restarted the arm, restarted pronterface and restarted the computer before and it kept happening. Now, the next day, it doesn't anymore..

I was directly sending G0 / G1 commands via the serial terminal and it was reliably using meters for the Y position. Whatever, now it doesn't anymore, I'll close this issue and post back here if it happens again and I find out what the issue is.

**Comment by simonemarin** [comment]
I can confirm the same issue, with the added problem that negative values on X are not working.
